modules/blog/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^articles$', views.articles_list, name="articles_list"),
    url(r'^articles/(?P<id>[0-9]+)$', views.article_detail, name="article_detail"),
    url(r'^articles/(?P<category_slug>[a-zA-Z0-9-_]+)$', views.articles_list, name="articles_by_category"),
    url(r'^like_article$', views.like_article, name='like_article'),
    url(r'^popular_category', views.popular_category, name='popular_category'),
    # url(r'^(?P<id>[0-9]+)$', views.article, name="article"),
    url(r'^lastnews$', views.last_news),
    url(r'^grants', views.grants, name="grants"),
    url(r'^about$', views.about_us, name="about_us"),
    url(r'^contact$', views.contacts, name="contacts"),
    url(r'^team$', views.team, name="team"),
    url(r'^best_practice$', views.best_practice, name="best_practice"),
    url(r'^partners$', views.partners, name="partners"),
    url(r'^search_articles', views.search_articles, name="search_articles"),
    url(r'^gallery/', include('photologue.urls', namespace='photologue')),
]




# article_detail


# best_practice
# partners

# like_articles
# last_grants

# index
# articles_list
# last_articles
# about_us
# contacts
# team
# live_stream

modules/newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

system/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.decorators.cache import never_cache
from django.views.i18n import javascript_catalog

from ckeditor_uploader import views as viewsck

from . import views, urls_modules
from .utils import decorated_includes, manage_condominium_permission
from .admin_site import DashboardSite

admin.site = DashboardSite()
admin.autodiscover()

from haystack.views import SearchView
from .forms import CustomSearchForm

urlpatterns = [
    # Index page
    url(r'^$', views.index, name='index'),
    # Condominium namespace
    url(r'^condominium/(?P<condominium_slug>[a-zA-Z0-9-_]+)/', include(urls_modules, namespace='condominium')),

    url(r'^search/', SearchView(form_class=CustomSearchForm), name='haystack_search'),
    # Admin namespace
    url(r'^manage/', decorated_includes(manage_condominium_permission, include(admin.site.urls))),
    # Accounts namespace
    url(r'^accounts/', include('allauth.urls')),
    url(r'^markdown/', include('django_markdown.urls')),
    url(r'^about/', views.about),
    url(r'^help/', views.help_page),
    url(r'^contacts', views.contacts),
    url(r'^instructions/', views.instructions),
    url(r'^load_coordinates$', views.load_condominium_coordinates, name='load_coordinates'),
    # Not sorted urls
    # TODO sort this urls in personal namespaces later. If it's possible.
    # url(r'^regions/', views.regions, name="regions"),
    url(r'^confirmyouremail',views.confirmyouremail),
    url(r'^profile/karma/+(?P<user_id>[0-9]+)',views.karma, name="karma"),
    url(r'^profile/+(?P<user_id>[0-9]+)$',views.profile, name="profile"),
    url(r'^profile/+(?P<user_id>[0-9]+)/edit/$', views.profile_edit, name='profile-edit'),
    url(r'^profile/+(?P<user_id>[0-9]+)/add_residence/$', views.residential_premise_create,
        name='residential-premise-create'),
    url(r'^profile/+(?P<user_id>[0-9]+)/add_non_residence/$', views.non_residential_premise_create,
        name='non-residential-premise-create'),
    url(r'^delete_residence/+(?P<pk>[0-9]+)$', views.residential_premise_delete,
        name='residential_premise_delete'),
    url(r'^delete_non_residence/+(?P<pk>[0-9]+)$', views.non_residential_premise_delete,
        name='non_residential_premise_delete'),
    url(r'^profile/+(?P<user_id>[0-9]+)/manage_utilites/$', views.manage_utilities, name='utilities-manage'),
    url(r'^profile/+(?P<user_id>[0-9]+)/condominium-update/$', views.update_condominiums, name='condominium_update'),
    url(r'^profile/userban/+(?P<user_id>[0-9]+)/+(?P<status>[0-9]+)',views.userban, name="userban"),
    url(r'^ckeditor/upload/', viewsck.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(viewsck).browse, name='ckeditor_browse'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':False}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':False}),
    url(r'^condominiumactivesearch$', views.condominium_active_search),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^managechoose/(?P<condominium_slug>[a-zA-Z0-9-_]+)/', views.redirect_to_manage),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^search', include('haystack.urls')),
    url(r'^condactivesearchformanage$', views.condominium_active_search_for_manage),
    url(r'^jsi18n/$', javascript_catalog, urls_modules.js_info_dict, name='javascript-catalog'),
    url(r'^filter-cities$', views.filter_cities, name='filter-cities'),
    url(r'^filter-condominiums', views.filter_condominiums, name='filter-condominiums'),

    # Blog
    url(r'^index/', include('blog.urls', namespace='blog')),

]

modules/blog/models.py
from django.db import models
from system.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from stdimage.models import StdImageField
import uuid
from system.validators import validate_file_extension
from django.utils.translation import ugettext_lazy as _

# генерируем псевдоуникальный файлнейм для загружаемых изображений
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'blog/%s' % filename

def get_document_path(instance, filename):
    ext = filename.split('.')
    filename = "{}_{}.{}".format(ext[0],instance.article.id,ext[-1])
    return 'blog/documents/%s' % filename


class Articles(models.Model):
    author = models.ForeignKey(User, db_column='author', verbose_name=_('Author'))
    datetime = models.DateTimeField(auto_now_add=True, verbose_name=_('Datetime'))
    datetime_publish = models.DateTimeField(verbose_name=_('Datetime_publish'))
    title = models.CharField(max_length=150, verbose_name=_('Title'))
    shortdesc = models.CharField(max_length=300, verbose_name=_('Short description'))
    text = RichTextUploadingField(verbose_name=_('News text'))
    mainimg = StdImageField(upload_to=get_file_path, variations={
        'large': (600, 400),
        'thumbnail': {"width": 70, "height": 60, "crop": True},
        'middle': {"width": 300, "height": 200, "crop": True}
    }, verbose_name=_('Main img'))
    publish = models.BooleanField(verbose_name=_('Publish'))
    categories = models.ManyToManyField('Category', blank=True, verbose_name=_('Categories'))


    class Meta:
        managed = True
        verbose_name = _('News')
        verbose_name_plural = _('your news')

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('Title'))
    slug = models.CharField(max_length=100, unique=True, verbose_name=_('slug'))

    def __str__(self):
        return self.title

    class Meta:
        managed = True
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        db_table = ''


class Like(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Articles)

    class Meta:
        unique_together = ('user', 'article')


class Documents(models.Model):
    article = models.ForeignKey(Articles)
    file = models.FileField(upload_to=get_document_path, validators=[validate_file_extension],
                                verbose_name=_('Docs'))

    def filename(self):
        # removed 'blog/documents/'
        return self.file.name[15:]

    class Meta:
        verbose_name = _('Document')
        verbose_name_plural = _('Documents')


class Photo(models.Model):
    image = models.ImageField(max_length=100, verbose_name=_('image'))
    article = models.ForeignKey(Articles, verbose_name=_('article'))

    class Meta:
        verbose_name = _('Photo')
        verbose_name_plural = _('Photo')

    def __str__(self):
        return _('Photo for article: ') + self.article.title

modules/blog/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import validate_slug

from .models import Category

from unidecode import unidecode
from re import match


class ArticlesAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticlesAdminForm, self).__init__(*args, **kwargs)
        self.fields['datetime_publish'].help_text = _('Enter date and time if you want to make deferred publication')
        self.fields['datetime_publish'].required = False
        # self.fields['public'].initial = self.current_condominium.public_news


class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']

    def clean(self):
        cleaned_data = super(AddCategoryForm, self).clean()
        title = cleaned_data.get('title')
        if match("^[\w ]+$", title):
            return cleaned_data
        else:
            raise forms.ValidationError(_('Name should consist of letters, numbers, underscores and spaces'))


class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        fields = ['title', 'slug']

    def clean(self):
        cleaned_data = super(UpdateCategoryForm, self).clean()
        title = cleaned_data.get('title')
        slug = unidecode(cleaned_data.get('slug'))

        if not match("^[\w ]+$", title):
            raise forms.ValidationError(_('Name should consist of letters, numbers, underscores and spaces'))

        try:
            validate_slug(slug)
        except forms.ValidationError:
            raise forms.ValidationError(_('Slug should consist of letters, numbers, underscores and dashes '))

        return cleaned_data

modules/blog/templates/blog/about.html
{% extends 'blog_base.html' %}

{% block content %}
        <!--colleft-->
        <div class="col-md-8 col-sm-12">
          <div class="about-block">
            <div class="about-head">
              <h1>Про нас</h1>
            </div>
            <div class="about-text">
              <p>Платформа «Розумне ОСББ» є ефективним інструментом по управлінню своїм будинком, житловим комплексом та прибудинковою територією. </p>
              <p>Мета платформи – підвищення якості життя в ОСББ за рахунок всебічного залучення мешканців до процесів розбудови ОСББ та підвищення публічності інформації. Дозволяє правлінню ОСББ та ревізійній групі оприлюднювати новини, інформацію щодо кошторисів, протоколів загальних зборів, зборів правління та інші важливі дані та документи. Мешканці обговорюють ідеї, подають та відслідковують заявки на вирішення проблем в ОСББ, беруть участь в опитуваннях правління.</p>
              <h4>Наступні перспективи розвитку платформи «Розумне ОСББ» передбачають:</h4>
              <ul>
                <li>Повний фінансового обліку ОСББ;</li>
                <li>Автоматичне формування кошторису та аналіз його виконання;</li>
                <li>Створення майданчику для комунікації мешканців та правління ОСББ з обслуговуючими та сервісними компаніями та фізичними особами;</li>
                <li>Надання інструменту асоціаціям ОСББ для ефективної взаємодії з владою</li>
              </ul>
            </div>
          </div>
        </div>
{% endblock content %}

modules/blog/templates/blog/article.html
{% extends 'blog_base.html' %}

{% block content %}

      <div class="col-md-8 col-sm-12">
        {% if article.youtube_video %}
            <div class="box-caption">
              <span>Video</span>
            </div>
            <div class="video-wrap">
                <div class='embed-container'><iframe src='{{ article.youtube_video }}' frameborder='0' allowfullscreen></iframe></div>
            </div>
        {% elif article.mainimg.url %}
            <div class="box-caption">
              <span>Новина</span>
            </div>
            <div><img src="{{ article.mainimg.url }}" /></div>
        {% else %}
        {% endif %}

        <div class="row">
            {% for photo in photos %}
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <a href="{{ photo.image.url }}" target="_blank">
                        <img src="{{ photo.image.url }}" class="thumbnail">
                    </a>
                </div>
            {% endfor %}
        </div>


        <!--post-detail-->
        <article class="post-detail">
          <h1>
            {{ article.title }}
          </h1>
          <div class="meta-post">
            <span>
                {{ article.author }}
            </span>
{#            <em></em>#}
            <span>
            {{ article.datetime_publish }}
            </span>
          </div>
          {% autoescape off %}{{ article.text }}{% endautoescape %}
            <div>
                <h5>Прикріплені документи:</h5>
                <ul>
                    {% for doc in article.documents_set.all %}
                        <li><a href="{{ doc.file.url }}">{{ doc.filename }}</a></li>
                    {% endfor %}
                </ul>
            </div>
          <h5 class="text-right font-heading"><strong>{{ article.author }}</strong> </h5>
          <h5 class="text-right font-heading">
                {% for category in article.categories.all %}
                   <a href="{% url 'blog:articles_by_category' category.slug %}">{{ category }}</a>|
                {% endfor %}
          </h5>
        </article>
        <!--social-detail-->
          <div class="social-detail">

          <span> Оцінити публікацю</span>
          <ul class="list-social-icon">
            <li>
                {% if user_like %}

                  <a class="like" style="cursor: pointer;">
                    <i class="fa fa-heart"></i>
                  </a>
                {% else %}

                  <a class="like" style="cursor: pointer;">
                    <i class="fa fa-heart-o"></i>
                  </a>
                {% endif %}
            </li>
            <li class="like_count">
                {{ likes_count }}
            </li>


          </ul>
        </div>
{#        <div class="social-detail">#}
{#          <span>   Share article</span>#}
{#          <ul class="list-social-icon">#}
{#            <li>#}
{#              <a href="#" class="facebook">#}
{#              <i class="fa fa-facebook"></i>#}
{#              </a>#}
{#            </li>#}
{#            <li>#}
{#              <a href="#" class="twitter">#}
{#              <i class="fa fa-twitter"></i>#}
{#              </a>#}
{#            </li>#}
{#             <li class="text-right">#}
{#              <a href="#" class="text-right">#}
{#              <i class="fa fa-twitter"></i>#}
{#              </a>#}
{#            </li>#}
{#          </ul>#}
{#        </div>#}
        <!--related post-->
        <div class="detail-caption">
          <span>Останні публікації</span>
        </div>
        <section class="spotlight-thumbs spotlight-thumbs-related">
          <div class="row">
              {% for last_article in articles %}
                <div class="col-md-4 col-sm-4 col-xs-12">
                  <div class="spotlight-item-thumb">
                    <div class="spotlight-item-thumb-img">
                      <a href="{% url 'blog:article_detail' last_article.id %}">
                      <img alt="" src="{{ last_article.mainimg.middle.url }}">
                      </a>
                    </div>
                    <h3><a href="{% url 'blog:article_detail' last_article.id %}">{{ last_article.title }}</a></h3>
                    <div class="meta-post">
                      <span >
                        {{ last_article.author }}
                      </span>
{#                      <em></em>#}
                      <span>
                        {{ last_article.datetime_publish }}
                      </span>
                    </div>
                  </div>
                </div>
              {% empty %}
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    ВІДСУТНІ
                  </div>
              {% endfor %}
          </div>
        </section>
      </div>

    <script>
    $('.like i').click(function () {
        $.ajax({
            type: "POST",
            url : "{% url 'blog:like_article' %}",
            data : {
                'user_id' : '{{ request.user.id }}',
                'article_id' : '{{ article.id }}'
            }
        });
        var current_value = parseInt($('.like_count').text());
        if ($(this).attr('class') == 'fa fa-heart-o'){
            $(this).attr('class','fa fa-heart')
            $('.like_count').text(current_value+1)
        }
        else {
            $(this).attr('class', 'fa fa-heart-o');
            $('.like_count').text(current_value-1)
        }

    });
    </script>

{% endblock %}

modules/blog/templates/blog/articles_list.html
{% extends 'blog_base.html' %}
{% load i18n %}

{% block content %}
        <div class="col-md-8 col-sm-12">
          <div class="box-caption">
              {% if category_title %}
                  <span>Новини по категорії {{ category_title}}</span>
              {% else %}
                  <span>Новини</span>
              {% endif %}
          </div>

          <div class="list-news-cate">
{#            <br/>#}
              {% for article in articles.object_list %}
                <article class="news-cate-item {% if forloop.first %}news-cate-item-first{% endif %}">
                  <div class="row">
                    <div class="col-md-5 col-sm-5 col-xs-12">

                      <a href="{% url 'blog:article_detail' article.id %}">
                        <img src="{{ article.mainimg.middle.url }}" />
                      </a>
                    </div>
                    <div class="col-md-7 col-sm-7 col-xs-12">
                      <h3><a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></h3>
                      <div class="meta-post">
                        <span>
                            {{ article.author }}
                        </span>
{#                        <em></em>#}
                        <span>
                            {{ article.datetime_publish }}
                        </span>


                          <span>
                          {% for category in article.categories.all %}
                            <a href="{% url 'blog:articles_by_category' category.slug %}">{{ category }} </a>|
                            {% endfor %}
                        </span>

                      </div>
                      <p>
                          {{ article.shortdesc }}
                      </p>
                    </div>
                  </div>
                </article>
              {% empty %}
                  Новин НЕМАЄ
              {% endfor %}

          </div>
{#    {% for person in articles.object_list %}#}
{#        <div>#}
{#            First name: {{ person }}#}
{#        </div>#}
{#    {% endfor %}#}

    <div class="paging">
        {% if articles.has_previous %}
            <a href="?{{ articles.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
        {% else %}
    {#        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>#}
        {% endif %}
        {% for page in articles.pages %}
            {% if page %}
                {% ifequal page articles.number %}
                    <span><a href="#" class="current">{{ page }}</a></span>
                {% else %}
                    <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                {% endifequal %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        {% if articles.has_next %}
            <a href="?{{ articles.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
        {% else %}
    {#        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>#}
        {% endif %}
    </div>


</div>

{% endblock content %}

modules/blog/templates/blog/best_practice.html
{% extends 'blog_base.html' %}

{% block content %}
      <<div class="col-md-8 col-sm-12">
        <h1>Кращі практики</h1>
        <h3>Дана сторінка, ще не наповнена!</h3>
      </div>
{% endblock content %}

modules/blog/templates/blog/index.html
{% extends 'blog_base.html' %}
{% load static %}
{% block content %}

        <!--colleft-->
        <div class="col-md-8 col-sm-12">
          <div class="box-caption">
            <span>Карта України по підключеним ОСББ</span>
          </div>
          <!--sportlight-->
          <div class="map-block" style="padding-bottom: 0%">

              <div id="map" ></div>
        <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>


        <script>
            function initMap() {
                var markers = [];
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 3,
                    center: {lat: 49.024, lng: 31.887}
                });

                {% for condominium in condominiums %}
                    var string = '{{ condominium.name|escapejs }}'.replace("ОСББ", '');
                    var label = string.match(/([^\s\"]+?)\w{0}/g)[0];
                    var marker{{ condominium.id }} = new google.maps.Marker({
                        position: {lat:Number('{{ condominium.latitude }}'), lng:Number('{{ condominium.longitude }}') },
                        label: label,
                        title: '{{ condominium.name|escapejs }}'
                    });
                    markers.push(marker{{ condominium.id }});

                    var infowindow{{ condominium.id }} = new google.maps.InfoWindow({
                        content: 'ОСББ "{{ condominium.name }}"'+
                            "<br/> {{ condominium.city.name }}"+
                            "<br/> Адреса реєстрації:{{ condominium.legal_address }}"+
                            "<br/><a href='../condominium/{{ condominium.slug }}/home' target=_blank><div class='pull-right'>перейти до ОСББ</div></a>"
                    });

                    google.maps.event.addListener(marker{{ condominium.id }}, 'click', function() {
                        infowindow{{ condominium.id }}.open(map,marker{{ condominium.id }});
                    });
                {% endfor %}

                // Add a marker clusterer to manage the markers.
                var markerCluster = new MarkerClusterer(map, markers,
                    {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});

            }

        </script>

          </div>
          <!--spotlight-thumbs-->

          <!--box-practices-->
          <section class="box-news">

          <div class="row">
              <div class="col-md-12">
                  <div class="page-head">
                      <h1>Новини ОСББ</h1>
                  </div>
              </div>
          </div>

          <div class="row">

              <div class="col-md-6 col-sm-6 col-xs-12">
                  <article class="news-two-large">
                      <a href="{% url 'blog:article_detail' second_article.id %}">
                        <img src="{{ second_article.mainimg.middle.url }}">
                      </a>
                      <h3>
                          <a href="{% url 'blog:article_detail' second_article.id %}">
                            {{ second_article.title }}
                          </a>
                      </h3>
                      <div class="meta-post">
                          <a href="{% url 'blog:article_detail' second_article.id %}">{{ second_article.author }}</a>
                          <em></em>
                          <span>{{ second_article.datetime_publish }}</span>
                      </div>
                      <p>{{ second_article.shortdesc }}</p>
                  </article>

                  <ul class="list-news-popular">
                    {% for article in half1_articles %}
                    <li>
                      <a href="{% url 'blog:article_detail' article.id %}">
                        <img src="{{ article.mainimg.middle.url }}" />
                      </a>
                      <h3><a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></h3>
                      <div class="meta-post">
                        <a href="#">{{ article.author }} </a>
                        <em></em>
                        <span> {{ article.datetime_publish }}  </span>
                      </div>
                    </li>
                    {% endfor %}
                  </ul>
              </div>

              <div class="col-md-6 col-sm-6 col-xs-12">
                  <article class="news-two-large">
                      <a href="{% url 'blog:article_detail' first_article.id %}">
                        <img src="{{ first_article.mainimg.middle.url }}">
                      </a>
                      <h3>
                          <a href="{% url 'blog:article_detail' first_article.id %}">
                            {{ first_article.title }}
                          </a>
                      </h3>
                      <div class="meta-post">
                          <a href="{% url 'blog:article_detail' first_article.id %}">{{ first_article.author }}</a>
                          <em></em>
                          <span>{{ first_article.datetime_publish }}</span>
                      </div>
                      <p>{{ first_article.shortdesc }}</p>
                  </article>

                  <ul class="list-news-popular">
                    {% for article in half2_articles %}
                    <li>
                      <a href="{% url 'blog:article_detail' article.id %}">
                        <img src="{{ article.mainimg.middle.url }}" />
                      </a>
                      <h3><a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></h3>
                      <div class="meta-post">
                        <a href="#">{{ article.author }} </a>
                        <em></em>
                        <span> {{ article.datetime_publish }}  </span>
                      </div>
                    </li>
                    {% endfor %}
                  </ul>
              </div>
            </div>
          </section>

          <!--box-practices-->
          <section class="box-news">
            <div class="box-caption">
              <span>ОСТАННІ ФОТО</span>
            </div>
            <div class="owl-carousel owl-review">
                {% for photo_info in photos_info %}
                  <div>
                    <article class="review-item">
                      <div class="review-img">
                        <img alt="" src="{{ photo_info.photo.image.url }}" class="img-responsive" />
                      </div>
                      <div class="review-item-caption">
                        <h3 class="font-heading" style="color: whitesmoke">
                              {{ photo_info.photo.caption }}
                          </h3>
                        <div class="meta-post">
                          <div style="float: left; color: whitesmoke;">
                            {{ photo_info.photo.date_added }}
                            </div>
                            {% if photo_info.gallery %}
                            <a href="{% url 'blog:photologue:pl-gallery' photo_info.gallery.slug %}">
                                <div style="color: whitesmoke; float: right;">
                                    Галерея: {{ photo_info.gallery }}
                                </div>
                            </a>
                            {% endif %}
                        </div>
                      </div>
                    </article>
                  </div>
                {% endfor %}
            </div>
          </section>

        <section>
            <div class="row">
                <div class="col-md-12">

                    <div id="news-feed" class="timeline">

                    </div>
                </div>
            </div>
        </section>
        </div>

        <script src="{% static 'blog/js/jquery.min.js' %}"></script>
        <script src="{% static 'blog/js/news-feed.js' %}"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key={{ api_key }}&callback=initMap">
        </script>

{% endblock %}

modules/blog/templates/blog/partners.html
{% extends 'blog_base.html' %}

{% block content %}
      <div class="col-md-8 col-sm-12">
        <h1>Партнери</h1>
        <h3>Дана сторінка, ще не наповнена!</h3>
      </div>
{% endblock content %}